### ISSUE TITLE
Error in Rails 5

### ISSUE THREAD

**Issue by joncameron** [samvera/om#70]
When using the latest Rails, I hit the following error on `newdoc.author = "Horn, Zoia"` while going through the "Tame Your XML with om" tutorial:
```
RuntimeError: can't modify frozen ActiveSupport::HashWithIndifferentAccess
from /Users/joncamer/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/hash_with_indifferent_access.rb:93:in `[]='
```

A method in document.rb is doing this: `changed_attributes['ng_xml'] = nil`
Which is no longer allowed.

Rails 5 method:
https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/activemodel/lib/active_model/dirty.rb#L216-L224

Rails 4.2 method:
```
# File activemodel/lib/active_model/dirty.rb, line 171
def changed_attributes
  @changed_attributes ||= ActiveSupport::HashWithIndifferentAccess.new
end
```

**Comment by jcoyne** [comment]
I believe this was fixed in 89d79e728ee0422c61f1a07a3be0f82d07a58363
