### ISSUE TITLE
Report coverage to Coveralls

### ISSUE THREAD

**Issue by tpendragon** [samvera/om#72]

**Comment by jrgriffiniii** [comment]
After resolving some difficulties in updating Gems for Ruby 2.4.4, this passes for me in a local development environment: https://github.com/samvera/om/compare/master...jrgriffiniii:issues-72-jrgriffiniii-coveralls-report?expand=1

However, it does not do consistently.  At times I have fully passing test suites, and others, some failures:
```
Finished in 1.14 seconds
358 examples, 3 failures, 27 pending

Failed examples:

rspec ./spec/unit/template_registry_spec.rb:40 # OM::XML::TemplateRegistry template definitions should contain predefined templates
rspec ./spec/integration/set_reentrant_terminology_spec.rb:27 # calling set_terminology more than once before cannot get bar
rspec ./spec/integration/set_reentrant_terminology_spec.rb:23 # calling set_terminology more than once before can get foo
```
